/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as SuperadminOrganizationsIndexRouteImport } from './routes/superadmin.organizations.index'
import { Route as AppTemplatesIndexRouteImport } from './routes/app.templates.index'
import { Route as AppStaffIndexRouteImport } from './routes/app.staff.index'
import { Route as AppSitesIndexRouteImport } from './routes/app.sites.index'
import { Route as AppPaymentsIndexRouteImport } from './routes/app.payments.index'
import { Route as AppInquiriesIndexRouteImport } from './routes/app.inquiries.index'
import { Route as AppCustomersIndexRouteImport } from './routes/app.customers.index'
import { Route as SuperadminOrganizationsNewRouteImport } from './routes/superadmin.organizations.new'
import { Route as SuperadminOrganizationsIdRouteImport } from './routes/superadmin.organizations.$id'
import { Route as AppStaffNewRouteImport } from './routes/app.staff.new'
import { Route as AppStaffIdRouteImport } from './routes/app.staff.$id'
import { Route as AppSitesNewRouteImport } from './routes/app.sites.new'
import { Route as AppPaymentsNewRouteImport } from './routes/app.payments.new'
import { Route as AppCustomersIdRouteImport } from './routes/app.customers.$id'
import { Route as AppSitesIdIndexRouteImport } from './routes/app.sites.$id.index'
import { Route as AppSitesIdPrintRouteImport } from './routes/app.sites.$id.print'
import { Route as AppSitesIdDesignerRouteImport } from './routes/app.sites.$id.designer'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperadminRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const SuperadminOrganizationsIndexRoute =
  SuperadminOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => SuperadminRoute,
  } as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesIndexRoute = AppSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppInquiriesIndexRoute = AppInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const SuperadminOrganizationsNewRoute =
  SuperadminOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SuperadminOrganizationsIdRoute =
  SuperadminOrganizationsIdRouteImport.update({
    id: '/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => SuperadminRoute,
  } as any)
const AppStaffNewRoute = AppStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIdRoute = AppStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesNewRoute = AppSitesNewRouteImport.update({
  id: '/sites/new',
  path: '/sites/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsNewRoute = AppPaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesIdIndexRoute = AppSitesIdIndexRouteImport.update({
  id: '/sites/$id/',
  path: '/sites/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesIdPrintRoute = AppSitesIdPrintRouteImport.update({
  id: '/sites/$id/print',
  path: '/sites/$id/print',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesIdDesignerRoute = AppSitesIdDesignerRouteImport.update({
  id: '/sites/$id/designer',
  path: '/sites/$id/designer',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/payments/new': typeof AppPaymentsNewRoute
  '/app/sites/new': typeof AppSitesNewRoute
  '/app/staff/$id': typeof AppStaffIdRoute
  '/app/staff/new': typeof AppStaffNewRoute
  '/superadmin/organizations/$id': typeof SuperadminOrganizationsIdRoute
  '/superadmin/organizations/new': typeof SuperadminOrganizationsNewRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/inquiries/': typeof AppInquiriesIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/sites/': typeof AppSitesIndexRoute
  '/app/staff/': typeof AppStaffIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
  '/superadmin/organizations/': typeof SuperadminOrganizationsIndexRoute
  '/app/sites/$id/designer': typeof AppSitesIdDesignerRoute
  '/app/sites/$id/print': typeof AppSitesIdPrintRoute
  '/app/sites/$id/': typeof AppSitesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/payments/new': typeof AppPaymentsNewRoute
  '/app/sites/new': typeof AppSitesNewRoute
  '/app/staff/$id': typeof AppStaffIdRoute
  '/app/staff/new': typeof AppStaffNewRoute
  '/superadmin/organizations/$id': typeof SuperadminOrganizationsIdRoute
  '/superadmin/organizations/new': typeof SuperadminOrganizationsNewRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/inquiries': typeof AppInquiriesIndexRoute
  '/app/payments': typeof AppPaymentsIndexRoute
  '/app/sites': typeof AppSitesIndexRoute
  '/app/staff': typeof AppStaffIndexRoute
  '/app/templates': typeof AppTemplatesIndexRoute
  '/superadmin/organizations': typeof SuperadminOrganizationsIndexRoute
  '/app/sites/$id/designer': typeof AppSitesIdDesignerRoute
  '/app/sites/$id/print': typeof AppSitesIdPrintRoute
  '/app/sites/$id': typeof AppSitesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/payments/new': typeof AppPaymentsNewRoute
  '/app/sites/new': typeof AppSitesNewRoute
  '/app/staff/$id': typeof AppStaffIdRoute
  '/app/staff/new': typeof AppStaffNewRoute
  '/superadmin/organizations/$id': typeof SuperadminOrganizationsIdRoute
  '/superadmin/organizations/new': typeof SuperadminOrganizationsNewRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/inquiries/': typeof AppInquiriesIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/sites/': typeof AppSitesIndexRoute
  '/app/staff/': typeof AppStaffIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
  '/superadmin/organizations/': typeof SuperadminOrganizationsIndexRoute
  '/app/sites/$id/designer': typeof AppSitesIdDesignerRoute
  '/app/sites/$id/print': typeof AppSitesIdPrintRoute
  '/app/sites/$id/': typeof AppSitesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/change-password'
    | '/login'
    | '/superadmin'
    | '/app/dashboard'
    | '/app/settings'
    | '/superadmin/dashboard'
    | '/app/customers/$id'
    | '/app/payments/new'
    | '/app/sites/new'
    | '/app/staff/$id'
    | '/app/staff/new'
    | '/superadmin/organizations/$id'
    | '/superadmin/organizations/new'
    | '/app/customers/'
    | '/app/inquiries/'
    | '/app/payments/'
    | '/app/sites/'
    | '/app/staff/'
    | '/app/templates/'
    | '/superadmin/organizations/'
    | '/app/sites/$id/designer'
    | '/app/sites/$id/print'
    | '/app/sites/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/change-password'
    | '/login'
    | '/superadmin'
    | '/app/dashboard'
    | '/app/settings'
    | '/superadmin/dashboard'
    | '/app/customers/$id'
    | '/app/payments/new'
    | '/app/sites/new'
    | '/app/staff/$id'
    | '/app/staff/new'
    | '/superadmin/organizations/$id'
    | '/superadmin/organizations/new'
    | '/app/customers'
    | '/app/inquiries'
    | '/app/payments'
    | '/app/sites'
    | '/app/staff'
    | '/app/templates'
    | '/superadmin/organizations'
    | '/app/sites/$id/designer'
    | '/app/sites/$id/print'
    | '/app/sites/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/change-password'
    | '/login'
    | '/superadmin'
    | '/app/dashboard'
    | '/app/settings'
    | '/superadmin/dashboard'
    | '/app/customers/$id'
    | '/app/payments/new'
    | '/app/sites/new'
    | '/app/staff/$id'
    | '/app/staff/new'
    | '/superadmin/organizations/$id'
    | '/superadmin/organizations/new'
    | '/app/customers/'
    | '/app/inquiries/'
    | '/app/payments/'
    | '/app/sites/'
    | '/app/staff/'
    | '/app/templates/'
    | '/superadmin/organizations/'
    | '/app/sites/$id/designer'
    | '/app/sites/$id/print'
    | '/app/sites/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/superadmin/organizations/': {
      id: '/superadmin/organizations/'
      path: '/organizations'
      fullPath: '/superadmin/organizations/'
      preLoaderRoute: typeof SuperadminOrganizationsIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/app/templates/': {
      id: '/app/templates/'
      path: '/templates'
      fullPath: '/app/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff/': {
      id: '/app/staff/'
      path: '/staff'
      fullPath: '/app/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/': {
      id: '/app/sites/'
      path: '/sites'
      fullPath: '/app/sites/'
      preLoaderRoute: typeof AppSitesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments/': {
      id: '/app/payments/'
      path: '/payments'
      fullPath: '/app/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inquiries/': {
      id: '/app/inquiries/'
      path: '/inquiries'
      fullPath: '/app/inquiries/'
      preLoaderRoute: typeof AppInquiriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/superadmin/organizations/new': {
      id: '/superadmin/organizations/new'
      path: '/organizations/new'
      fullPath: '/superadmin/organizations/new'
      preLoaderRoute: typeof SuperadminOrganizationsNewRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/organizations/$id': {
      id: '/superadmin/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/superadmin/organizations/$id'
      preLoaderRoute: typeof SuperadminOrganizationsIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/app/staff/new': {
      id: '/app/staff/new'
      path: '/staff/new'
      fullPath: '/app/staff/new'
      preLoaderRoute: typeof AppStaffNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff/$id': {
      id: '/app/staff/$id'
      path: '/staff/$id'
      fullPath: '/app/staff/$id'
      preLoaderRoute: typeof AppStaffIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/new': {
      id: '/app/sites/new'
      path: '/sites/new'
      fullPath: '/app/sites/new'
      preLoaderRoute: typeof AppSitesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments/new': {
      id: '/app/payments/new'
      path: '/payments/new'
      fullPath: '/app/payments/new'
      preLoaderRoute: typeof AppPaymentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/$id': {
      id: '/app/customers/$id'
      path: '/customers/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/$id/': {
      id: '/app/sites/$id/'
      path: '/sites/$id'
      fullPath: '/app/sites/$id/'
      preLoaderRoute: typeof AppSitesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/$id/print': {
      id: '/app/sites/$id/print'
      path: '/sites/$id/print'
      fullPath: '/app/sites/$id/print'
      preLoaderRoute: typeof AppSitesIdPrintRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/$id/designer': {
      id: '/app/sites/$id/designer'
      path: '/sites/$id/designer'
      fullPath: '/app/sites/$id/designer'
      preLoaderRoute: typeof AppSitesIdDesignerRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppPaymentsNewRoute: typeof AppPaymentsNewRoute
  AppSitesNewRoute: typeof AppSitesNewRoute
  AppStaffIdRoute: typeof AppStaffIdRoute
  AppStaffNewRoute: typeof AppStaffNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInquiriesIndexRoute: typeof AppInquiriesIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppSitesIndexRoute: typeof AppSitesIndexRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
  AppSitesIdDesignerRoute: typeof AppSitesIdDesignerRoute
  AppSitesIdPrintRoute: typeof AppSitesIdPrintRoute
  AppSitesIdIndexRoute: typeof AppSitesIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppPaymentsNewRoute: AppPaymentsNewRoute,
  AppSitesNewRoute: AppSitesNewRoute,
  AppStaffIdRoute: AppStaffIdRoute,
  AppStaffNewRoute: AppStaffNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInquiriesIndexRoute: AppInquiriesIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppSitesIndexRoute: AppSitesIndexRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
  AppSitesIdDesignerRoute: AppSitesIdDesignerRoute,
  AppSitesIdPrintRoute: AppSitesIdPrintRoute,
  AppSitesIdIndexRoute: AppSitesIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SuperadminRouteChildren {
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminOrganizationsIdRoute: typeof SuperadminOrganizationsIdRoute
  SuperadminOrganizationsNewRoute: typeof SuperadminOrganizationsNewRoute
  SuperadminOrganizationsIndexRoute: typeof SuperadminOrganizationsIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminOrganizationsIdRoute: SuperadminOrganizationsIdRoute,
  SuperadminOrganizationsNewRoute: SuperadminOrganizationsNewRoute,
  SuperadminOrganizationsIndexRoute: SuperadminOrganizationsIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
