// PDF export helpers using jsPDF + autoTable.
// Used for: payment receipts, customer statements, master plan snapshots.

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { money, fmtDate } from "@/data/selectors";
import type { Transaction, Customer, Site, Plot, InstallmentStage, Booking } from "@/data/types";

const BRAND = "PropertyWala";

function header(doc: jsPDF, title: string, subtitle?: string) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(BRAND, 14, 18);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text("Developer Edition", 14, 24);
  doc.setTextColor(0);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 38);
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(subtitle, 14, 44);
    doc.setTextColor(0);
  }
  doc.setDrawColor(200);
  doc.line(14, 48, 196, 48);
}

function footer(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by ${BRAND} · ${new Date().toLocaleString()}`,
      14,
      doc.internal.pageSize.getHeight() - 8,
    );
    doc.text(
      `Page ${i} / ${pages}`,
      doc.internal.pageSize.getWidth() - 30,
      doc.internal.pageSize.getHeight() - 8,
    );
    doc.setTextColor(0);
  }
}

/** Payment receipt — single transaction */
export function downloadReceiptPDF(tx: Transaction) {
  const doc = new jsPDF();
  header(doc, "Payment Receipt", `Receipt #${tx.id.slice(-8).toUpperCase()}`);

  autoTable(doc, {
    startY: 56,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 3 },
    body: [
      ["Date", fmtDate(tx.transaction_date)],
      ["Party", tx.party_name],
      ["Type", tx.type.replace(/_/g, " ")],
      ["Payment mode", tx.payment_mode],
      ["Direction", tx.direction === "IN" ? "Money In" : "Money Out"],
      ["Notes", tx.notes ?? "—"],
    ],
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 40, textColor: [90, 90, 90] } },
  });

  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 14;
  doc.setFillColor(245, 240, 225);
  doc.rect(14, finalY, 182, 22, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("AMOUNT", 20, finalY + 9);
  doc.setFontSize(20);
  doc.text(money(tx.amount), 190, finalY + 15, { align: "right" });

  if (tx.receipt_url && tx.receipt_url.startsWith("data:image")) {
    try {
      doc.addPage();
      header(doc, "Receipt attachment");
      doc.addImage(tx.receipt_url, "JPEG", 14, 56, 180, 200);
    } catch {
      /* ignore image errors */
    }
  }

  footer(doc);
  doc.save(`receipt-${tx.id.slice(-8)}.pdf`);
}

/** Customer statement — full booking + schedule + transactions */
export function downloadCustomerStatementPDF(args: {
  customer: Customer;
  booking: Booking | null;
  plot: Plot | null;
  site: Site | null;
  stages: InstallmentStage[];
  transactions: Transaction[];
  paid: string;
}) {
  const { customer, booking, plot, site, stages, transactions, paid } = args;
  const doc = new jsPDF();
  header(doc, "Statement of Account", customer.full_name);

  autoTable(doc, {
    startY: 56,
    theme: "plain",
    styles: { fontSize: 9, cellPadding: 2 },
    body: [
      ["Phone", customer.phone],
      ["Email", customer.email],
      ...(site ? [["Site", site.name]] : []),
      ...(plot
        ? [
            [
              "Plot",
              `${plot.plot_number} · ${plot.area} ${site?.area_unit === "SQFT" ? "sq ft" : "sq m"}`,
            ],
          ]
        : []),
      ...(booking
        ? [
            ["Booking date", fmtDate(booking.booking_date)],
            ["Total sale price", money(booking.total_sale_price)],
            ["Paid so far", money(paid)],
            [
              "Balance",
              money(String(Math.max(0, Number(booking.total_sale_price) - Number(paid)))),
            ],
          ]
        : []),
    ],
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 40, textColor: [90, 90, 90] } },
  });

  if (stages.length) {
    autoTable(doc, {
      startY: (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6,
      head: [["Stage", "Due", "Amount", "Paid", "Status"]],
      headStyles: { fillColor: [45, 55, 72] },
      body: stages.map((s) => [
        s.stage_name,
        fmtDate(s.due_date),
        money(s.amount_due),
        money(s.paid_amount),
        s.status,
      ]),
    });
  }

  if (transactions.length) {
    autoTable(doc, {
      startY: (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6,
      head: [["Date", "Reference", "Mode", "Amount"]],
      headStyles: { fillColor: [45, 55, 72] },
      body: transactions.map((t) => [
        fmtDate(t.transaction_date),
        t.type,
        t.payment_mode,
        money(t.amount),
      ]),
    });
  }

  footer(doc);
  doc.save(`statement-${customer.full_name.replace(/\s+/g, "-")}.pdf`);
}

/** Master plan — captures the SVG element into the PDF */
export async function downloadMasterPlanPDF(site: Site, plots: Plot[], svgEl: SVGSVGElement | null) {
  const doc = new jsPDF({ orientation: "landscape", format: "a3" });
  header(doc, `Master Plan — ${site.name}`, site.address);

  if (svgEl) {
    try {
      const serializer = new XMLSerializer();
      const svgStr = serializer.serializeToString(svgEl);
      const svgBlob = new Blob([svgStr], { type: "image/svg+xml;charset=utf-8" });
      const url = URL.createObjectURL(svgBlob);
      const img = new Image();
      const dataUrl: string = await new Promise((resolve, reject) => {
        img.onload = () => {
          const canvas = document.createElement("canvas");
          canvas.width = img.width * 2 || 1600;
          canvas.height = img.height * 2 || 1000;
          const ctx = canvas.getContext("2d");
          if (!ctx) return reject(new Error("no ctx"));
          ctx.fillStyle = "#F5F0DC";
          ctx.fillRect(0, 0, canvas.width, canvas.height);
          ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
          resolve(canvas.toDataURL("image/jpeg", 0.9));
        };
        img.onerror = reject;
        img.src = url;
      });
      URL.revokeObjectURL(url);
      doc.addImage(dataUrl, "JPEG", 10, 55, 400, 220);
    } catch {
      /* skip on error */
    }
  }

  doc.addPage();
  header(doc, "Plot register", site.name);
  autoTable(doc, {
    startY: 56,
    head: [["#", "Plot", "Length", "Width", "Area", "Facing", "Type", "Price", "Status"]],
    headStyles: { fillColor: [45, 55, 72] },
    body: plots.map((p, i) => [
      i + 1,
      p.plot_number,
      p.length,
      p.width,
      p.area,
      p.facing,
      p.plot_type,
      money(p.price),
      p.status,
    ]),
  });

  footer(doc);
  doc.save(`master-plan-${site.name.replace(/\s+/g, "-")}.pdf`);
}
